# Generated by Django 5.0.6 on 2024-05-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
            ],
            options={
                'verbose_name': 'Админы',
                'verbose_name_plural': 'Админы',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('no_media', 'Без медиа'), ('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ')], help_text='Тип медиа', max_length=50, verbose_name='Тип медиа')),
                ('text', models.TextField(blank=True, help_text='Текст рассылки', max_length=4096, null=True, verbose_name='Текст')),
                ('file_id', models.CharField(blank=True, help_text='File ID медиа рассылки', max_length=255, null=True, verbose_name='File ID')),
                ('date_malling', models.DateTimeField(help_text='Дата рассылки', verbose_name='Дата')),
                ('is_sent', models.BooleanField(default=False, help_text='Статус отправки', verbose_name='Статус отправки')),
            ],
            options={
                'verbose_name': 'Рассылки',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('telegram_id', models.PositiveBigIntegerField(null=True, verbose_name='Идентификатор Telegram')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Имя пользователя')),
                ('block', models.BooleanField(default=False, verbose_name='Бан')),
                ('ref_code', models.CharField(max_length=255, unique=True, verbose_name='Код верификации')),
                ('fio', models.CharField(max_length=255, null=True, verbose_name='ФИО пользователя')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
        migrations.CreateModel(
            name='InviteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('fio', models.CharField(max_length=255, null=True, verbose_name='ФИО пользователя')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Номер телефона')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admin_panel.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
