# Generated by Django 5.0.6 on 2024-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='number_account',
            field=models.CharField(max_length=255, null=True, verbose_name='Счет'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='passport',
            field=models.CharField(max_length=255, null=True, verbose_name='Паспорт'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='uniq_code_pdf',
            field=models.PositiveBigIntegerField(default=1, unique=True, verbose_name='Код верификации PDF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tguser',
            name='yookassa_payment_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Id платеж юкассы рекурентный'),
        ),
    ]
