# Generated by Django 5.0.6 on 2024-05-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_tguser_number_account_tguser_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='uniq_code_pdf',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Код верификации PDF'),
        ),
    ]
