# Generated by Django 5.0.6 on 2024-05-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_tguser_uniq_code_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='YookassaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key_yookassa', models.CharField(max_length=500, verbose_name='Токен для оплаты в юкассы')),
                ('shop_id', models.PositiveBigIntegerField(verbose_name='ShopId юкассы')),
                ('price', models.PositiveBigIntegerField(verbose_name='Цена подписки')),
                ('bot_url', models.CharField(max_length=500, verbose_name='Урл бота')),
            ],
            options={
                'verbose_name': 'Юкасса аккаунт',
                'verbose_name_plural': 'Юкасса аккаунты',
            },
        ),
        migrations.AlterField(
            model_name='tguser',
            name='uniq_code_pdf',
            field=models.CharField(max_length=255, null=True, verbose_name='Код верификации PDF'),
        ),
    ]
