# Generated by Django 5.0.6 on 2024-05-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_tguser_expire_date_subscribe_tguser_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=400, unique=True, verbose_name='Пользователь')),
                ('work_time', models.IntegerField(verbose_name='Количесвто часов в работе')),
                ('wt_hour', models.CharField(max_length=400, verbose_name='Потребление, кВт/ час')),
                ('sum_wt_hour', models.CharField(max_length=400, verbose_name='Суммарное потребление, кВт')),
                ('sum_two_wt_hour', models.CharField(max_length=400, verbose_name='Суммарное потребление 2, кВт')),
                ('tariff', models.CharField(max_length=400, verbose_name='Тариф')),
                ('main', models.CharField(max_length=400, verbose_name='Управление')),
                ('pay_main', models.CharField(max_length=400, verbose_name='Итог к оплате')),
                ('month', models.DateField(verbose_name='Месяц')),
            ],
        ),
    ]
