# Generated by Django 5.0.6 on 2024-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_report_options_report_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='expire_date_subscribe',
            field=models.DateField(null=True, verbose_name='Дата окончания платежа'),
        ),
    ]
