# Generated by Django 5.0.6 on 2024-06-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_tguser_expire_date_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='api_key',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tguser',
            name='secret_key',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
