# Generated by Django 5.0.6 on 2024-06-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_tguser_api_key_tguser_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteuser',
            name='api_key',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
