# Generated by Django 5.0.6 on 2024-06-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_inviteuser_workers_tguser_by_report_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_workers', to='admin_panel.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
    ]
