# Generated by Django 5.0.6 on 2024-06-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_workeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='status_asccount',
            field=models.BooleanField(default=False),
        ),
    ]
