# Generated by Django 5.0.6 on 2024-06-24 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_tguser_status_asccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_buy', to='admin_panel.tguser')),
            ],
            options={
                'verbose_name': 'Заявка на покупку',
                'verbose_name_plural': 'Заявки на покупку',
            },
        ),
        migrations.CreateModel(
            name='ApplicationsSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_sell', to='admin_panel.tguser')),
            ],
            options={
                'verbose_name': 'Заявка на продажу',
                'verbose_name_plural': 'Заявки на продажу',
            },
        ),
    ]
