# Generated by Django 5.0.6 on 2024-06-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_applicationsbuy_applicationssell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='secret_key',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='uniq_code_pdf',
        ),
        migrations.AlterField(
            model_name='applicationsbuy',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Закрыта заявка'),
        ),
        migrations.AlterField(
            model_name='applicationssell',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Закрыта заявка'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='expire_date_subscribe',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания платежа'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='status_asccount',
            field=models.BooleanField(default=False, verbose_name='Договор подписан'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id платеж юкассы рекурентный'),
        ),
    ]
