# Generated by Django 5.0.6 on 2024-08-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_remove_tguser_secret_key_remove_tguser_uniq_code_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Для рассылки', max_length=255, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа рассылки',
                'verbose_name_plural': 'Группы рассылки',
            },
        ),
        migrations.AlterField(
            model_name='tguser',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='by_report_month',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчет за месяц'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='corr_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Корр. счет'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='date_passport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО пользователя'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='get_passport',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='number_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='passport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='inviteuser',
            name='group',
            field=models.ManyToManyField(related_name='invites', to='admin_panel.groupuser', verbose_name='Группа рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='group',
            field=models.ManyToManyField(related_name='mailings', to='admin_panel.groupuser', verbose_name='Группа рассылки'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='group',
            field=models.ManyToManyField(related_name='users', to='admin_panel.groupuser', verbose_name='Группа рассылки'),
        ),
    ]
