# Generated by Django 5.0.6 on 2024-08-06 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_groupuser_remove_report_usdt_alter_tguser_bank_bik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admin_panel.tguser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
