"""
Django settings for BotInvest project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import tempfile
from pathlib import Path

from environ import Env
from import_export.formats.base_formats import XLSX
from loguru import logger

from BotInvest.loguru_django import LoguruInterceptHandler

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = Env(
    DEBUG=(bool, False)
)
env.read_env(Path(BASE_DIR, '.env'))

SECRET_KEY = env.str('SECRET_KEY')

TG_TOKEN_BOT = env.str('TG_TOKEN_BOT')

REDIS_URL = env('REDIS_URL')

REDIS_HOST = env.str('REDIS_HOST')
CONVERT_URL = env.str('CONVERT_URL')
SECRET_API = env.str('SECRET_API')
REDIS_PORT = env.str('REDIS_PORT')

DEBUG = env.bool('DEBUG')

LINK_BOT = env.str('LINK_BOT')

ALLOWED_HOSTS = env.list(
    'ALLOWED_HOSTS',
    default=[
        '127.0.0.1', 'localhost',
        'beae-95-24-22-18.ngrok-free.app'
    ]
)

CSRF_TRUSTED_ORIGINS = env.list(
    'CSRF_TRUSTED_ORIGINS',
    default=[
        'http://127.0.0.1:8080',
        'https://beae-95-24-22-18.ngrok-free.app'

    ]
)

logger.info(CSRF_TRUSTED_ORIGINS)

ADMIN_ORDER_MODELS = [
    {
        'Настройки Бота': [
            'TextBot', 'BotButtons', 'TextPhoto',
],
        'Телеграмм': [
            'Mailing', 'Admin', 'TgUser',
        ],
    },
    ]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin_panel',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BotInvest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BotInvest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': env.db_url('DATABASE_URL', default='sqlite:///my-local-sqlite.db'),
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

STATIC_URL = '/static/'
MEDIA_URL = '/media/'



MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LANGUAGE_CODE = 'Ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'loguru_console': {
            '()': LoguruInterceptHandler,
            'level': 1,
        },
    },
    'loggers': {
        '': {
            'handlers': ['loguru_console'],
            'level': "INFO",
            'propagate': True,
        },
        'django.server': {
            'handlers': ['loguru_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['loguru_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['loguru_console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['loguru_console'],
    },
}

EXPORT_FORMATS = [XLSX]
IMPORT_EXPORT_FORMATS = [XLSX]
FILE_UPLOAD_TEMP_DIR = tempfile.gettempdir()